version: '3'
services:
  redis:
    image: redis:4.0.14-alpine
  app:
    build: .
    command: npm run start:prod
    environment: 
      NODE_ENV: production
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - redis